on:
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: "Forge Tests + Gas 🧪"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.2.3

      - name: Install dependencies
        run: forge install

      - name: Run forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run tests with fuzzing
        run: forge test -vvv --gas-report
